# Generated by Django 4.2.4 on 2023-08-30 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', tinymce.models.HTMLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='home/')),
                ('key_point_1', models.CharField(max_length=255)),
                ('key_point_2', models.CharField(max_length=255)),
                ('key_point_3', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(upload_to='blog_images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('company_and_year', models.CharField(max_length=255)),
                ('job_summary', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.TextField()),
                ('title', models.CharField(max_length=255)),
                ('title_summary', models.CharField(max_length=255)),
                ('main_title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='home/')),
                ('how_i_work_1_title', models.CharField(max_length=255)),
                ('how_i_work_1_summary', models.TextField()),
                ('how_i_work_2_title', models.CharField(max_length=255)),
                ('how_i_work_2_summary', models.TextField()),
                ('how_i_work_3_title', models.CharField(max_length=255)),
                ('how_i_work_3_summary', models.TextField()),
                ('how_i_work_4_title', models.CharField(max_length=255)),
                ('how_i_work_4_summary', models.TextField()),
                ('strategy_title_1', models.CharField(max_length=255)),
                ('strategy_summary_1', models.TextField()),
                ('strategy_title_2', models.CharField(max_length=255)),
                ('strategy_summary_2', models.TextField()),
                ('strategy_title_3', models.CharField(max_length=255)),
                ('strategy_summary_3', models.TextField()),
                ('strategy_title_4', models.CharField(max_length=255)),
                ('strategy_summary_4', models.TextField()),
                ('side_title', models.CharField(max_length=255)),
                ('side_summary', models.TextField()),
                ('side_key_point_1', models.CharField(max_length=255)),
                ('side_key_point_2', models.CharField(max_length=255)),
                ('side_key_point_3', models.CharField(max_length=255)),
                ('side_key_point_4', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sub_title', models.CharField(max_length=255)),
                ('overview', models.TextField()),
                ('highlight', models.TextField()),
                ('content1', models.TextField()),
                ('code', tinymce.models.HTMLField()),
                ('content2', models.TextField()),
                ('image', models.ImageField(upload_to='blog_images/')),
                ('cate_name', models.CharField(max_length=500)),
                ('featured', models.BooleanField(default='Select')),
                ('view_count', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('slug', models.SlugField(max_length=250, null=True, unique=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.author')),
                ('blog_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='App.category')),
                ('favourites', models.ManyToManyField(default=None, related_name='favourite', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(to='App.tag')),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
    ]
