# Generated by Django 4.2.4 on 2023-08-30 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='favourites',
        ),
    ]
