# Generated by Django 4.2.4 on 2023-09-03 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_remove_blog_favourites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='how_i_work_1_summary',
            new_name='how_i_work_text',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='how_i_work_2_summary',
            new_name='key_features_1_summary',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='how_i_work_1_title',
            new_name='key_features_1_title',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='how_i_work_3_summary',
            new_name='key_features_2_summary',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='how_i_work_2_title',
            new_name='key_features_2_title',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='how_i_work_4_summary',
            new_name='key_features_3_summary',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='how_i_work_3_title',
            new_name='key_features_3_title',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='strategy_summary_1',
            new_name='key_features_4_summary',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='how_i_work_4_title',
            new_name='key_features_4_title',
        ),
        migrations.RemoveField(
            model_name='services',
            name='strategy_summary_2',
        ),
        migrations.RemoveField(
            model_name='services',
            name='strategy_summary_3',
        ),
        migrations.RemoveField(
            model_name='services',
            name='strategy_summary_4',
        ),
        migrations.RemoveField(
            model_name='services',
            name='strategy_title_1',
        ),
        migrations.RemoveField(
            model_name='services',
            name='strategy_title_2',
        ),
        migrations.RemoveField(
            model_name='services',
            name='strategy_title_3',
        ),
        migrations.RemoveField(
            model_name='services',
            name='strategy_title_4',
        ),
    ]
