# Generated by Django 4.2.4 on 2023-09-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_rename_how_i_work_1_summary_services_how_i_work_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='key_features_5_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='key_features_5_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='key_features_6_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='key_features_6_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
