# Generated by Django 4.2.4 on 2023-09-04 20:37

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_services_key_features_5_summary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='code',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='content2',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='sub_title',
        ),
        migrations.AlterField(
            model_name='blog',
            name='content1',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='highlight',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='blog',
            name='overview',
            field=tinymce.models.HTMLField(),
        ),
    ]
