# Generated by Django 4.2.4 on 2023-09-06 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_remove_blog_code_remove_blog_content2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='next_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next', to='App.blog'),
        ),
        migrations.AddField(
            model_name='blog',
            name='previous_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous', to='App.blog'),
        ),
    ]
