# Generated by Django 4.2.4 on 2023-09-06 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_blog_next_post_blog_previous_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='next_post',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='previous_post',
        ),
    ]
