# Generated by Django 4.2.4 on 2023-09-06 13:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0007_remove_blog_next_post_remove_blog_previous_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='favourites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
