# Generated by Django 4.2.4 on 2023-09-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_subscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, null=True, upload_to='document/')),
            ],
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='document',
        ),
        migrations.AddField(
            model_name='subscribe',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='subscribe',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='subscribe',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
