# Generated by Django 4.2.4 on 2023-09-07 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_mycv_remove_subscribe_document_subscribe_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mycv',
            old_name='document',
            new_name='pdf_file',
        ),
        migrations.AddField(
            model_name='mycv',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
